"use client";

type ReportItem = {
  name: string;
  type: string;
  date: string;
  generatedBy: string;
  format: string;
};

type Props = {
  data?: ReportItem[];
  loading?: boolean;
};

function formatBadge(type: string) {
  switch ((type || "").toLowerCase()) {
    case "sale":
      return "bg-blue-50 text-blue-700";
    case "inventory":
      return "bg-amber-50 text-amber-700";
    case "financial":
      return "bg-emerald-50 text-emerald-700";
    case "users":
      return "bg-violet-50 text-violet-700";
    default:
      return "bg-slate-100 text-slate-700";
  }
}

export default function ReportsTable({
  data = [],
  loading = false,
}: Props) {
  return (
    <div className="overflow-hidden rounded-2xl border border-[#EEF2F6] bg-white shadow-sm">
      <div className="border-b border-[#F1F5F9] px-4 py-4 sm:px-6">
        <h3 className="text-[16px] font-semibold text-[#0F172A]">
          Generated Reports
        </h3>
        <p className="mt-1 text-[12px] text-[#64748B]">
          Download and review generated reports
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full min-w-[820px]">
          <thead className="bg-[#F8FAFC]">
            <tr>
              {[
                "Report Name",
                "Type",
                "Generated Date",
                "Generated By",
                "Format",
                "Action",
              ].map((head) => (
                <th
                  key={head}
                  className="px-4 py-4 text-left text-[13px] font-medium text-[#475569] sm:px-6"
                >
                  {head}
                </th>
              ))}
            </tr>
          </thead>

          <tbody>
            {loading ? (
              Array.from({ length: 6 }).map((_, i) => (
                <tr key={i} className="border-t border-[#F1F5F9]">
                  {Array.from({ length: 6 }).map((__, j) => (
                    <td key={j} className="px-4 py-4 sm:px-6">
                      <div className="h-4 w-full animate-pulse rounded bg-gray-100" />
                    </td>
                  ))}
                </tr>
              ))
            ) : data.length > 0 ? (
              data.map((r, i) => (
                <tr
                  key={i}
                  className="border-t border-[#F1F5F9] transition hover:bg-[#FAFCFF]"
                >
                  <td className="px-4 py-4 text-[14px] font-medium text-[#0F172A] sm:px-6">
                    {r.name}
                  </td>

                  <td className="px-4 py-4 sm:px-6">
                    <span
                      className={`inline-flex rounded-full px-2.5 py-1 text-[12px] font-medium ${formatBadge(
                        r.type
                      )}`}
                    >
                      {r.type}
                    </span>
                  </td>

                  <td className="px-4 py-4 text-[14px] text-[#64748B] sm:px-6">
                    {r.date}
                  </td>

                  <td className="px-4 py-4 text-[14px] text-[#64748B] sm:px-6">
                    {r.generatedBy}
                  </td>

                  <td className="px-4 py-4 text-[14px] text-[#64748B] sm:px-6">
                    {r.format}
                  </td>

                  <td className="px-4 py-4 sm:px-6">
                    <button className="text-[14px] font-medium text-[#2563EB] hover:underline">
                      Download
                    </button>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td
                  colSpan={6}
                  className="px-4 py-10 text-center text-sm text-[#64748B] sm:px-6"
                >
                  No reports found
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}