export default function ReportsTable() {
  const reports = new Array(10).fill({
    name: "Monthly Sales Report - January 2026",
    type: "Sale",
    date: "04-02-2026",
    by: "Admin",
    format: "PDF",
  });

  return (
    <div className="bg-white rounded-2xl border border-[#EEF2F6] shadow-sm overflow-x-auto">
      <table className="w-full min-w-[900px]">
        <thead className="bg-[#F8FAFC]">
          <tr>
            {[
              "Report Name",
              "Type",
              "Generated Date",
              "Generated By",
              "Format",
              "Action",
            ].map((head) => (
              <th
                key={head}
                className="px-6 py-4 text-left text-[13px] font-medium text-[#475569]"
              >
                {head}
              </th>
            ))}
          </tr>
        </thead>

        <tbody>
          {reports.map((r, i) => (
            <tr key={i} className="border-t border-[#F1F5F9]">
              <td className="px-6 py-4 text-[14px] text-[#0F172A]">
                {r.name}
              </td>
              <td className="px-6 py-4 text-[14px] text-[#64748B]">
                {r.type}
              </td>
              <td className="px-6 py-4 text-[14px] text-[#64748B]">
                {r.date}
              </td>
              <td className="px-6 py-4 text-[14px] text-[#64748B]">
                {r.by}
              </td>
              <td className="px-6 py-4 text-[14px] text-[#64748B]">
                {r.format}
              </td>
              <td className="px-6 py-4">
                <button className="text-[#2563EB] text-[14px] hover:underline">
                  Download
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
